// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjteX7ostE1ltCJgm99LdXD2KQFB3FTA0',
    appId: '1:126375604224:web:fec13c69a06b45356be8e5',
    messagingSenderId: '126375604224',
    projectId: 'sakura-24223',
    authDomain: 'sakura-24223.firebaseapp.com',
    storageBucket: 'sakura-24223.firebasestorage.app',
    measurementId: 'G-LD0LELEK2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XtmFkZWHmGWP_9NAgxiHMaAIv1HCPyg',
    appId: '1:126375604224:android:390b449c469d3fe16be8e5',
    messagingSenderId: '126375604224',
    projectId: 'sakura-24223',
    storageBucket: 'sakura-24223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlAUU7r5ukw-EoIvQ3NB_98ZvR3sqcft4',
    appId: '1:126375604224:ios:e66b1d94e48de5a66be8e5',
    messagingSenderId: '126375604224',
    projectId: 'sakura-24223',
    storageBucket: 'sakura-24223.firebasestorage.app',
    iosBundleId: 'com.example.sakura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlAUU7r5ukw-EoIvQ3NB_98ZvR3sqcft4',
    appId: '1:126375604224:ios:e66b1d94e48de5a66be8e5',
    messagingSenderId: '126375604224',
    projectId: 'sakura-24223',
    storageBucket: 'sakura-24223.firebasestorage.app',
    iosBundleId: 'com.example.sakura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjteX7ostE1ltCJgm99LdXD2KQFB3FTA0',
    appId: '1:126375604224:web:3c9f48d9da15396f6be8e5',
    messagingSenderId: '126375604224',
    projectId: 'sakura-24223',
    authDomain: 'sakura-24223.firebaseapp.com',
    storageBucket: 'sakura-24223.firebasestorage.app',
    measurementId: 'G-EJCLCHW2ZK',
  );
}
